version: 2.1
jobs:
  build:
    docker: 
      - image: mankalo/akeyless_cli # the primary container, where your job's commands are run
    environment:
      myvar: foo
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Setting Akeyless CLI
          command: mkdir ~/.akeyless && echo -e 'dns="vault.staging.akeyless.dev"\nprotocol="https"' > ~/.akeyless/settings
      - run:
          name: Get Akeyless Token
          command: akeyless configure --admin-email $admin_email --admin-password aaa
      - run:
          name: Fetch Secret
          command: cat ~/.akeyless/profiles/default.toml
