version: 2.1
jobs:
  build:
    docker: 
      - image: mankalo/akeyless_cli # the primary container, where your job's commands are run
    environment:
      myvar: akeyless://test
      BASH_ENV: ~/.akeyless/akeyless_env.sh
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Get Akeyless Token
          command: akeyless auth --admin-email $admin_email --admin-password $admin_password
      - run:
          name: Fetch Secret
          command: bash -x ~/.akeyless/akeyless_env.sh && echo "test=[$myvar]"
