version: 2.1
jobs:
  build:
    docker: 
      - image: mankalo/akeyless_cli # the primary container, where your job's commands are run
    environment:
      myvar: foo
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Setting Akeyless CLI
          command: mkdir ~/.akeyless && echo -e 'dns="vault.staging.akeyless.dev"\nprotocol="https"' > ~/.akeyless/settings
      - run:
          name: Test Akeyless CLI
          command: akeyless -h
