version: 2.1
jobs:
  build:
    docker: 
      - image: akeyless/ci_base
    environment:
      ACCESS_PASSWORD: akeyless://mySecret
      AWS_JIT_CREDS: akeyless://AWS_producer
      BASH_ENV: ~/.akeyless/akeyless_env.sh
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Authenticate to Akeyless
          command: akeyless auth --admin-email $admin_email --admin-password $admin_password
      - run:
          name: Fetch Secret
          command: echo "ACCESS_PASSWORD=$ACCESS_PASSWORD" && echo "AWS_JIT_CREDS=$AWS_JIT_CREDS"
